# Generated by Django 4.1.5 on 2023-01-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_patient_answer1_alter_patient_answer2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthgoal', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
