# Generated by Django 4.1.5 on 2023-01-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_healthgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=50)),
                ('particulartest', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
