# Generated by Django 4.1.5 on 2023-01-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='specificanswer4',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion4',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
