# Generated by Django 4.1.5 on 2023-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_test_code_test_test_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='none', max_length=100),
        ),
    ]
