# Generated by Django 4.1.5 on 2023-02-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
