# Generated by Django 4.1.5 on 2023-02-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_test_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_link',
            field=models.CharField(default='non', max_length=500),
        ),
        migrations.AddField(
            model_name='test',
            name='test_reason',
            field=models.CharField(default='non', max_length=500),
        ),
    ]
