# Generated by Django 4.1.5 on 2023-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_otpmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='testlink',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
