# Generated by Django 4.1.5 on 2023-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_patient_testlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.CharField(default='non', max_length=1000),
        ),
    ]
