# Generated by Django 4.1.5 on 2023-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_test_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='history_answer',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
