# Generated by Django 4.1.5 on 2023-03-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_patient_history_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='history_answer',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
