# Generated by Django 4.1.5 on 2023-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_patient_history_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='buttons_clear',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='comments',
            field=models.CharField(default='none', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='healthgoal_clear',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='questions_clear',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='rating',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='tests_clear',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
