# Generated by Django 4.1.5 on 2023-03-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_patient_historyfemale_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='historyfemale_answer',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='historyfemale_question',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
