# Generated by Django 4.1.5 on 2023-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_patient_historyfemale_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='number',
        ),
        migrations.AddField(
            model_name='patient',
            name='contacted',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
