# Generated by Django 4.1.5 on 2023-03-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_patient_number_patient_contacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contacted',
        ),
        migrations.AddField(
            model_name='patient',
            name='number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
