# Generated by Django 4.1.5 on 2023-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_patient_contacted_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contacted',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
