# Generated by Django 4.1.5 on 2023-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_patient_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
