# Generated by Django 4.1.5 on 2023-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_patient_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contacted1',
            field=models.BooleanField(default=False),
        ),
    ]
