# Generated by Django 4.1.5 on 2023-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_patient_contacted1'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contacted',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
