# Generated by Django 4.1.5 on 2023-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_patient_contacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contacted1',
        ),
        migrations.AlterField(
            model_name='patient',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
